language: node_js
node_js:
- '0.10'
before_script:
- node_modules/.bin/jspm install
script: node_modules/karma/bin/karma start karma.conf.js --single-run
deploy:
  provider: npm
  email: djindjic@gmail.com
  api_key:
    secure: Zdga1tNJCHOZxzesTJwaE5Lkteqg5wNC1R9wlrX/wXwowuV0Ehwli3rp378O9UWAj5x16JZ3oXD1GBIjvpt4+YWTzoJAxZdltV3Qmv6VhzH/rv0JQTMFGSe+/CxlUv2nWxvfFOjjfevY1JNI/2Yy6D0ckvizKxqT/ynTZhGlSTI=
  on:
    tags: true
    all_branches: true
