language: node_js
sudo: false
node_js:
- '0.12'
before_script:
  - npm install -g jspm
  - npm install -g karma-cli
  - npm install -g divshot-cli
  - jspm config endpoints.github.auth $JSPM_AUTH
  - jspm install
script:
  - karma start karma.conf.js --single-run
deploy:
  provider: npm
  email: djindjic@gmail.com
  api_key:
    secure: Zdga1tNJCHOZxzesTJwaE5Lkteqg5wNC1R9wlrX/wXwowuV0Ehwli3rp378O9UWAj5x16JZ3oXD1GBIjvpt4+YWTzoJAxZdltV3Qmv6VhzH/rv0JQTMFGSe+/CxlUv2nWxvfFOjjfevY1JNI/2Yy6D0ckvizKxqT/ynTZhGlSTI=
  on:
    tags: true
    all_branches: true
